在 JavaScript 中，可以使用 `window.onerror` 方法来全局捕获运行时错误。当页面中出现 JavaScript 运行时错误时，`window.onerror` 方法会被触发，可以在这个方法中对错误进行处理。

例如，以下代码演示了如何使用 `window.onerror` 方法来全局捕获 JavaScript 运行时错误：

```javascript
window.onerror = function (message, source, lineno, colno, error) {
  console.log("Error:", message);
  console.log("Source:", source);
  console.log("Line:", lineno);
  console.log("Column:", colno);
  console.log("Error object:", error);
};

// 故意抛出一个错误
foo.bar();
```

在这个例子中，我们定义了一个 `window.onerror` 方法，在这个方法中打印出错误信息、错误源、行号、列号和错误对象。然后我们故意抛出一个错误（调用一个不存在的函数），这会触发 `window.onerror` 方法并输出错误信息。注意，`window.onerror` 只能捕获运行时错误，不能捕获语法错误。

## React 中如何全局捕获错误？

在 React 中，可以使用 `componentDidCatch` 方法来捕获全局错误。当组件内部发生错误时，React 会调用这个方法，并传入错误信息和错误对象，可以在这个方法中对错误进行处理。

例如，以下代码演示了如何在 React 中捕获全局错误：

```javascript
class ErrorBoundary extends React.Component {
  constructor(props) {
    super(props);
    this.state = { hasError: false };
  }

  componentDidCatch(error, errorInfo) {
    console.log('Error:', error);
    console.log('Error info:', errorInfo);
    this.setState({ hasError: true });
  }

  render() {
    if (this.state.hasError) {
      return <h1>Something went wrong.</h1>;
    }

    return this.props.children;
  }
}

class MyApp extends React.Component {
  render() {
    return (
      <ErrorBoundary>
        <MyComponent />
      </ErrorBoundary>
    );
  }
}

// MyComponent 中故意抛出一个错误
class MyComponent extends React.Component {
  render() {
    throw new Error('Something went wrong.');
  }
}

ReactDOM.render(<MyApp />, document.getElementById('root'));
```
在这个例子中，我们定义了一个 ErrorBoundary 组件，它包装了要渲染的子组件，并定义了一个 `componentDidCatch` 方法来捕获错误。当子组件中发生错误时，`componentDidCatch` 方法会被调用，并将错误信息和错误对象作为参数传入。在这个方法中，我们打印出错误信息和错误对象，并将 hasError 状态设置为 true。如果 hasError 状态为 true，则渲染一个错误页面，否则渲染子组件。

> 注意，`componentDidCatch` 方法只能捕获子组件中的错误，无法捕获在组件外部发生的错误。如果要捕获全局错误，可以将 ErrorBoundary 组件放在应用的根组件中，以便捕获所有组件中的错误。
